[2025-03-11T03:03:15.290+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_data_stream.job_data_stream manual__2025-03-11T03:03:14.370170+00:00 [queued]>
[2025-03-11T03:03:15.307+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_data_stream.job_data_stream manual__2025-03-11T03:03:14.370170+00:00 [queued]>
[2025-03-11T03:03:15.308+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-11T03:03:15.325+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): job_data_stream> on 2025-03-11 03:03:14.370170+00:00
[2025-03-11T03:03:15.330+0000] {standard_task_runner.py:57} INFO - Started process 59 to run task
[2025-03-11T03:03:15.335+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'job_data_stream', 'job_data_stream', 'manual__2025-03-11T03:03:14.370170+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/data_stream.py', '--cfg-path', '/tmp/tmpvym5p_7k']
[2025-03-11T03:03:15.337+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask job_data_stream
[2025-03-11T03:03:15.450+0000] {task_command.py:415} INFO - Running <TaskInstance: job_data_stream.job_data_stream manual__2025-03-11T03:03:14.370170+00:00 [running]> on host 0431913abdf0
[2025-03-11T03:03:15.609+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dii' AIRFLOW_CTX_DAG_ID='job_data_stream' AIRFLOW_CTX_TASK_ID='job_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T03:03:14.370170+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T03:03:14.370170+00:00'
[2025-03-11T03:03:15.618+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.11', 29092)]>: connecting to broker:29092 [('172.18.0.11', 29092) IPv4]
[2025-03-11T03:03:15.619+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-11T03:03:15.621+0000] {conn.py:422} ERROR - Connect attempt to <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.11', 29092)]> returned error 111. Disconnecting.
[2025-03-11T03:03:15.622+0000] {conn.py:928} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.11', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-03-11T03:03:15.623+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.11', 29092)]>: connecting to broker:29092 [('172.18.0.11', 29092) IPv4]
[2025-03-11T03:03:15.624+0000] {conn.py:422} ERROR - Connect attempt to <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.11', 29092)]> returned error 111. Disconnecting.
[2025-03-11T03:03:15.625+0000] {conn.py:928} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.11', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-03-11T03:03:15.627+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_stream.py", line 31, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'])
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 241, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 918, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-03-11T03:03:15.653+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=job_data_stream, task_id=job_data_stream, execution_date=20250311T030314, start_date=20250311T030315, end_date=20250311T030315
[2025-03-11T03:03:15.676+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task job_data_stream (NoBrokersAvailable; 59)
[2025-03-11T03:03:15.719+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-11T03:03:15.770+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
